name = "Jib"
uuid = "f310f2d2-a263-11e8-3998-47bd686f18f7"
authors = ["Luca Billi <noreply.section+dev@gmail.com>"]
version = "0.20.4"

[deps]
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"

[weakdeps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

[extensions]
DataFramesExt = "DataFrames"

[compat]
DataFrames = "1.0"
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0" # Required by julia < 1.9 package manager.

[targets]
test = ["Test", "DataFrames"]
